### ISSUE TITLE
Where is the extension stored?

### ISSUE THREAD

**Issue by redxtech** [modfin/pg-xid#8]
I'm wondering where the extension is stored in the database itself.

I'm wanting to use this extension for an app, but the database will be served with containers, and the container and host will be swapped out fairly often, but the database storage will be retained of course.

From what I can tell by looking at `xid.sql`, and based on how you have to specify a database during install, it looks like everything is installed at the database level, with nothing else to worry about.

Just wanting to confirm that is the case.

Thanks!

**Comment by crholm** [comment]
Well, it's not really a postgres extension, but rather  a domain, a sequence and a few function, which are all stored in the public namespace/schema of your selected database. ie `DROP DATABASE...` will remove the it from the instance. 

In general, swapping out the container or the node and attaching the storage to the new one shouldn't pose any problems. Just as you would expect your tables and data to remain, domains, sequence and functions do as well.

**Comment by redxtech** [comment]
That makes sense.

Thanks!

**Comment by crholm** [comment]
Np

**Comment by patrickmichalina** [comment]
@redxtech checkout https://github.com/VADOSWARE/pg_idkit for a rust extension of xid.
